spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qing?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    #???
    username: root #???
    password: root #??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.bean #??mapper.xml???????
server: #????
  port: 8081

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.bean #??mapper.xml???????
